# Setup
title: 'Missing Semester'
url: https://afnom.github.io
domain: afnom.github.io
baseurl: /missing-semester/

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/New_York
analytics:
  tracking_id: G-P7WVHD84D1

collections:
  '2019':
    output: true
  '2020':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
